#!/usr/bin/env python3

import datetime
import json
import pathlib




doc_file: pathlib.Path = pathlib.Path('./dist/doc.json').resolve()
ap_file: pathlib.Path = pathlib.Path('./dist/assetpairs.txt').resolve()


if __name__ == '__main__':
    ap_list: str = "\n".join(json.loads(doc_file.read_text())['assetpairs'])
    ap_list = f"# Asset pairs Data knows about\n# Last updated {datetime.datetime.fromtimestamp(doc_file.stat().st_mtime).strftime('%Y-%m-%d')}\n\n{ap_list}"
    ap_file.write_text(ap_list)
