#!/usr/bin/env python3

import datetime
import pathlib
import zoneinfo




timezones_file: pathlib.Path = (pathlib.Path(__file__).parent / 'dist' / 'timezones.txt').resolve()
timezones: list[str] = sorted(list(zoneinfo.available_timezones()))

file_content: str = f"# Timezones Data knows about. Last updated {datetime.datetime.now().strftime('%Y-%m-%d')}\n\n"
file_content += '\n'.join(timezones)

timezones_file.write_text(data=file_content)
